apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoplay
  namespace: argocd
spec:
  project: default
  source:
    # UPDATE THIS to your actual repository URL
    repoURL: 'https://github.com/lreh/argoplay.git'
    targetRevision: HEAD
    path: k8s # Ensure this points to the folder containing your deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true